DROP DATABASE IF EXISTS restaurantservice;
DROP USER IF EXISTS `restaurant_service`@`%`;
CREATE DATABASE IF NOT EXISTS restaurantservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `restaurant_service`@`%` IDENTIFIED WITH mysql_native_password BY 'akhtar';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
    CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `restaurantservice`.* TO `restaurant_service`@`%`;
FLUSH PRIVILEGES;